{% set version = "1.3.0" %}
{% set sha256 = "f831166d6ec100ff3c77d8d6025378af957db5ad8bb908ec10dd5333d6b0d927" %}

package:
  name: cargo-bundle-licenses
  version: {{ version }}

source:
  url: https://github.com/sstadick/cargo-bundle-licenses/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - pkg-config
    - make
    - cmake
    - libgit2
    - zlib
  host:
    - libgit2
    - zlib

test:
  commands:
    - cargo-bundle-licenses --help

about:
  home: https://github.com/sstadick/cargo-bundle-licenses
  license: MIT
  license_family: MIT
  license_file: LICENSE-MIT
  summary: Bundle thirdparty licenses for Cargo projects into a single file.

extra:
  recipe-maintainers:
    - sstadick
