{% set version = "0.4.0" %}
{% set sha256 = "0f19406cbf9e7ad68b68e5738c218c3395986648e5b60cf97cd52e732e82590c" %}

package:
  name: cargo-bundle-licenses
  version: {{ version }}

source:
  url: https://github.com/sstadick/cargo-bundle-licenses/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - pkg-config
    - make
    - cmake
    - libgit2
  host:
    - zlib

test:
  commands:
    - cargo-bundle-licenses --help

about:
  home: https://github.com/sstadick/cargo-bundle-licenses
  license: MIT
  license_family: MIT
  license_file: LICENSE-MIT
  summary: Bundle thirdparty licenses for Cargo projects into a single file.

extra:
  recipe-maintainers:
    - sstadick
